theme: jekyll-theme-midnight
title: About Me
description: Reflecting on Introduction to Digital Humanities
nav: 
- title: "Home"
url: lilliea121.github.io
title: "About Me"
url: lilliea121.github.io/aboutme
