theme: jekyll-theme-midnight
title: Lillie Abella's Digital Humanities Portfolio
description: What I've been up to this semester!
nav: 
- title: "Home"
url: lilliea121.github.io
title: "About Me"
url: lilliea121.github.io/aboutme
